-- 코드를 입력하세요
SELECT M.CART_ID
FROM (SELECT CART_ID FROM CART_PRODUCTS WHERE NAME='Yogurt') Y JOIN (SELECT CART_ID FROM CART_PRODUCTS WHERE NAME='Milk') M ON Y.CART_ID=M.CART_ID
GROUP BY M.CART_ID
ORDER BY M.CART_ID
