SELECT INFO.ITEM_ID, INFO.ITEM_NAME, INFO.RARITY
FROM (SELECT IT.PARENT_ITEM_ID
FROM ITEM_INFO II JOIN ITEM_TREE IT ON II.ITEM_ID=IT.ITEM_ID
GROUP BY IT.PARENT_ITEM_ID
HAVING IT.PARENT_ITEM_ID IS NOT NULL) PARENT
RIGHT JOIN ITEM_INFO INFO ON PARENT.PARENT_ITEM_ID=INFO.ITEM_ID
WHERE PARENT.PARENT_ITEM_ID IS NULL
ORDER BY INFO.ITEM_ID DESC