WITH SIZE AS (
    SELECT MAX(ID) AS "SIZE_OF_TABLE"
    FROM ECOLI_DATA
)

SELECT ID, (
    CASE 
        WHEN RANKING<=SIZE_OF_TABLE*0.25 THEN "CRITICAL" 
        WHEN RANKING<=SIZE_OF_TABLE*0.5 THEN "HIGH" 
        WHEN RANKING<=SIZE_OF_TABLE*0.75 THEN "MEDIUM" 
        ELSE "LOW" 
    END
    )
    AS `COLONY_NAME` 
FROM (
    SELECT rank() over (ORDER BY SIZE_OF_COLONY DESC) AS 'RANKING', ID, SIZE_OF_COLONY
    FROM ECOLI_DATA
    ) SC JOIN SIZE
ORDER BY ID