-- 코드를 입력하세요
SELECT O.ANIMAL_ID, O.ANIMAL_TYPE, O.NAME
FROM ANIMAL_INS I JOIN ANIMAL_OUTS O ON I.ANIMAL_ID=O.ANIMAL_ID
WHERE SUBSTR(I.SEX_UPON_INTAKE,1,6)='Intact' && (SUBSTR(O.SEX_UPON_OUTCOME,1,6)='Spayed' || SUBSTR(O.SEX_UPON_OUTCOME,1,8)='Neutered')
ORDER BY O.ANIMAL_ID