-- 코드를 입력하세요
SELECT PRICE AS PRICE_GROUP, count(PRODUCT_ID) AS PRODUCTS
FROM (
    SELECT PRODUCT_ID, TRUNCATE(PRICE/10000, 0)*10000 AS PRICE
    FROM PRODUCT
) PRODUCT
GROUP BY PRICE
ORDER BY PRICE_GROUP