-- 코드를 입력하세요
SELECT P.PRODUCT_CODE AS CATEGORY, COUNT(*) AS PRODUCTS
FROM (
    SELECT SUBSTR(PRODUCT_CODE,1,2) AS PRODUCT_CODE, PRODUCT_ID
    FROM PRODUCT
) P
GROUP BY P.PRODUCT_CODE
ORDER BY `CATEGORY`