-- 코드를 입력하세요
SELECT B.DATETIME AS HOUR, COUNT(B.DATETIME) AS COUNT
FROM (
    SELECT TRUNCATE((DATETIME%1000000)/10000,0) AS DATETIME
    FROM ANIMAL_OUTS
) B
WHERE B.DATETIME>=9 && B.DATETIME<=19
GROUP BY B.DATETIME
ORDER BY B.DATETIME