WITH MAX_REVIEW AS (
    SELECT *
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    ORDER BY COUNT(MEMBER_ID) DESC
    LIMIT 1
), MEMBER_REVIEW AS (
    SELECT MP.MEMBER_NAME, RR.REVIEW_TEXT, RR.REVIEW_DATE, RR.MEMBER_ID
    FROM MEMBER_PROFILE MP JOIN REST_REVIEW RR ON MP.MEMBER_ID=RR.MEMBER_ID
)

SELECT ME.MEMBER_NAME, ME.REVIEW_TEXT, DATE_FORMAT(ME.REVIEW_DATE, "%Y-%m-%d") AS `REVIEW_DATE`
FROM MEMBER_REVIEW ME JOIN MAX_REVIEW MA ON ME.MEMBER_ID=MA.MEMBER_ID
ORDER BY REVIEW_DATE, ME.REVIEW_TEXT