SELECT I.ITEM_ID, I.ITEM_NAME, I.RARITY
FROM (
    SELECT IT.ITEM_ID
    FROM ITEM_INFO II JOIN ITEM_TREE IT ON II.ITEM_ID=IT.PARENT_ITEM_ID
    WHERE II.RARITY="RARE"
    ORDER BY II.ITEM_ID) P 
    JOIN 
    ITEM_INFO I 
    ON P.ITEM_ID=I.ITEM_ID
ORDER BY I.ITEM_ID DESC