SELECT MS.SCORE, HE.EMP_NO, HE.EMP_NAME, HE.POSITION, HE.EMAIL
FROM (SELECT EMP_NO, SUM(SCORE) AS 'SCORE'
    FROM HR_GRADE
    GROUP BY EMP_NO
    ORDER BY SUM(SCORE) DESC
    LIMIT 1) MS 
    JOIN 
    HR_EMPLOYEES HE 
    ON MS.EMP_NO=HE.EMP_NO